GET http://localhost:3000/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJjZWxzciIsImVtYWlsIjoiY2Vsc3IxM0BnbWFpbC5jb20iLCJpYXQiOjE3NTIyNjc1MzMsImV4cCI6MTc1MjI3MTEzM30.CAUhgCtIKLQTg3fe0ci8z0-iQL74qct-U__FClc2NKY
Content-Type: application/json

###

POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Faiq Subhi Ramadlan",
    "username": "celsr",
    "email": "celsr13@gmail.com",
    "password": "passwordTest"
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "usernameOrEmail": "celsr",
    "password": "passwordTest"
}

###