GET http://localhost:3000/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJjZWxzcjEiLCJlbWFpbCI6ImNlbHNyMTMxQGdtYWlsLmNvbSIsImlhdCI6MTc1MjgyMDcxOSwiZXhwIjoxNzUyODI0MzE5fQ.tkP2Wdyzs3zc9Fn7KfXjKR7vwFWR_Gxcc0_QsYO1LgQ
Content-Type: application/json

###

POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "firstName": "Faiq Subhi Ramadlan",
    "username": "celsr1",
    "email": "celsr131@gmail.com",
    "password": "passwordTest"
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "usernameOrEmail": "celsr131@gmail.com",
    "password": "passwordTest"
}

###


PUT http://localhost:3000/api/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJjZWxzcjEiLCJlbWFpbCI6ImNlbHNyMTMxQGdtYWlsLmNvbSIsImlhdCI6MTc1MjgyMDcxOSwiZXhwIjoxNzUyODI0MzE5fQ.tkP2Wdyzs3zc9Fn7KfXjKR7vwFWR_Gxcc0_QsYO1LgQ

{
    "gender" : "p",
    "firstName": "Faiq",
    "lastName": "Subhi Ramadlan"
}